### ISSUE TITLE
Problem loading start page

### ISSUE THREAD

**Issue by illustribe** [lucaseverett/toolbar-dial#23]
Hello, nice addon!
Just that in firefox when opening a new window (or starting a new session) the extension isn't loading correctly, message: 
File not found
Firefox can’t find the file at moz-extension://4547a75f-a139-af4f-a708-7f6d70b92957/dist/index.html.
but afterwards one I create a new tab then it does work well. Just a heads up :)
thanks and cheers!

**Comment by lucaseverett** [comment]
Hi @illustribe! Thank you for the note! This is due to a Firefox bug. The only workaround at the moment is to disable and then re-enable the extension.

I've reported the bug to Mozilla, but there isn't anything I can do on my end to fix it. Disabling and then re-enabling will get it back up and running for you though!

**Comment by illustribe** [comment]
Ok great, all the best with that! :)
