### ISSUE TITLE
Link to Home button

### ISSUE THREAD

**Issue by trevoraylett** [lucaseverett/toolbar-dial#25]
Firstly, a big thanks for Toolbar-dial, it's making my life easier!! but I have a suggestion that could make it easier still - Certainly for us Brave Browser users (well me anyway!) it would be useful if Toolbar-dial could be linked to the Home button on the browser so that wherever I am in the bowels of my bookmarks I can always click the home button to go to my default folder top level.  I know I can select "new tab" for a similar result but that means opening a new tab page which means I very quickly end up with a whole host of open tabs - not really what I am looking for.  What I want is to be able to go "Home" from the page that I am on without having any new tabs open. (Hope that's explained it ok)  In the meantime, keep up the good work, it's without doubt an extension well worth having!

**Comment by lucaseverett** [comment]
Hi @trevoraylett! Thank you for the kind note. I'm glad you enjoy using Toolbar Dial!

Within Brave Settings, there is an option under "Show home button" to use the "New Tab page". Have you perhaps changed it to a custom address in the past? If so, if you change it back to "New Tab page" that will get it working so that when clicking the home button it will load Toolbar Dial.
